image : claudiababescu/dotnet-core-aws-build
stages:
  - build
cache:
  key: "$CI_JOB_NAME"
  paths:
    - node_modules/
release:
 stage: build
 script:
  - echo $AWS_CREDENTIALS_JSON | base64 -d > aws-credentials.json
  - npm install
  - npm run buildprod
  - grunt build
  - npm run s3
 only:
   - master
dev:
 stage: build
 script:
  - echo $AWS_DEV_CREDENTIALS_JSON | base64 -d > aws-credentials.json
  - npm install
  - npm run buildprod
  - grunt build
  - npm run s3dev
 only:
   - develop